name             'ossec'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
source_url       'https://github.com/sous-chefs/ossec'
issues_url       'https://github.com/sous-chefs/ossec'
description      'Installs and configures ossec'
version          '2.0.2'
chef_version     '>= 15.3'

supports 'debian'
supports 'ubuntu'
supports 'redhat'
supports 'centos'
supports 'fedora'
supports 'scientific'
supports 'oracle'
supports 'amazon'

depends 'yum-atomic'
